name: test mainline
on: push
  branches:
    - "master"

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.18", "1.17.8", "1.17.6"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
            go-version: ${{ matrix.go_version }}
      - run: go test -v -count=1 ./...
